### ISSUE TITLE
npm install is failing for the jsx tutorial

### ISSUE THREAD

**Issue by protoEvangelion** [metal/metaljs.com#60] opened 2017-08-04 21:53 UTC
![image](https://user-images.githubusercontent.com/20076677/28984120-3d7180b2-7911-11e7-880a-817b97240080.png)

When following the tutorial and downloading the `Boilerplate with JSX` zip folder, I'm getting these errors on the front end:

```err
incremental-dom-cjs.js:1398 Uncaught ReferenceError: exports is not defined
    at incremental-dom-cjs.js:1398
    at incremental-dom-cjs.js:1419
    at Modal.js:32

(anonymous) @ Modal.js:32
index.html:15 Uncaught TypeError: metal.Modal is not a constructor at index.html:15
```

**Comment by robframpton** [comment] 2017-08-04 23:06
We might need to see if gulp-metal has a regression, as that's what is used to build these demos.

On another note, we might as well update these boilerplates to a webpack build, since that's what we are using internally.

**Comment by protoEvangelion** [comment] 2017-08-04 23:20
I'm also getting this same error when generating the boilerplate with the **metal Yeoman generator**.

Is there a correlation?

**Comment by robframpton** [comment] 2017-10-27 21:26
Closing as the tutorials have been refactored to use webpack instead of gulp-metal.

**Closed as completed by robframpton** 2017-10-27 21:26 UTC
